name: Build PyInstaller
on:
  push:
  schedule:
    - cron: '15 16 * * 3,6'

jobs:
  build:
    name: Build package
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: pyinstaller/pyinstaller
          ref: v4.3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build 64-bit bootloader
        run: |
          cd bootloader
          python waf distclean all --target-arch=64bit

      - name: Build 32-bit bootloader
        run: |
          cd bootloader
          python waf distclean all --target-arch=32bit

      - name: Build packages
        run: |
          python -m pip install wheel
          python setup.py sdist bdist_wheel

      - name: Archive packages
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*
